# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/store.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/store.proto\x12\x10\x64istributedstore\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\" \n\x0fSlowdownRequest\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x05\"#\n\x10SlowdownResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0eRestoreRequest\"\"\n\x0fRestoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\".\n\x10\x43\x61nCommitRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"-\n\x0f\x44oCommitRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0e\x44oAbortRequest\"\"\n\x0f\x44oAbortResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xae\x04\n\rKeyValueStore\x12\x42\n\x03put\x12\x1c.distributedstore.PutRequest\x1a\x1d.distributedstore.PutResponse\x12\x42\n\x03get\x12\x1c.distributedstore.GetRequest\x1a\x1d.distributedstore.GetResponse\x12Q\n\x08slowDown\x12!.distributedstore.SlowdownRequest\x1a\".distributedstore.SlowdownResponse\x12N\n\x07restore\x12 .distributedstore.RestoreRequest\x1a!.distributedstore.RestoreResponse\x12Q\n\tcanCommit\x12\".distributedstore.CanCommitRequest\x1a .distributedstore.CommitResponse\x12O\n\x08\x64oCommit\x12!.distributedstore.DoCommitRequest\x1a .distributedstore.CommitResponse\x12N\n\x07\x64oAbort\x12 .distributedstore.DoAbortRequest\x1a!.distributedstore.DoAbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=39
  _globals['_PUTREQUEST']._serialized_end=79
  _globals['_PUTRESPONSE']._serialized_start=81
  _globals['_PUTRESPONSE']._serialized_end=111
  _globals['_GETREQUEST']._serialized_start=113
  _globals['_GETREQUEST']._serialized_end=138
  _globals['_GETRESPONSE']._serialized_start=140
  _globals['_GETRESPONSE']._serialized_end=183
  _globals['_SLOWDOWNREQUEST']._serialized_start=185
  _globals['_SLOWDOWNREQUEST']._serialized_end=217
  _globals['_SLOWDOWNRESPONSE']._serialized_start=219
  _globals['_SLOWDOWNRESPONSE']._serialized_end=254
  _globals['_RESTOREREQUEST']._serialized_start=256
  _globals['_RESTOREREQUEST']._serialized_end=272
  _globals['_RESTORERESPONSE']._serialized_start=274
  _globals['_RESTORERESPONSE']._serialized_end=308
  _globals['_CANCOMMITREQUEST']._serialized_start=310
  _globals['_CANCOMMITREQUEST']._serialized_end=356
  _globals['_DOCOMMITREQUEST']._serialized_start=358
  _globals['_DOCOMMITREQUEST']._serialized_end=403
  _globals['_COMMITRESPONSE']._serialized_start=405
  _globals['_COMMITRESPONSE']._serialized_end=438
  _globals['_DOABORTREQUEST']._serialized_start=440
  _globals['_DOABORTREQUEST']._serialized_end=456
  _globals['_DOABORTRESPONSE']._serialized_start=458
  _globals['_DOABORTRESPONSE']._serialized_end=492
  _globals['_EMPTY']._serialized_start=494
  _globals['_EMPTY']._serialized_end=501
  _globals['_KEYVALUESTORE']._serialized_start=504
  _globals['_KEYVALUESTORE']._serialized_end=1062
# @@protoc_insertion_point(module_scope)
